name: build_image_spdk_core_amd

on:
  workflow_run:
    workflows: ["build_image_spdk_core_arm"]
    types:
      - completed


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Set branch name from triggered workflow
      run: echo "BRANCH_NAME=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_ENV


    - name: Build the docker image
      run: docker build --file docker/Dockerfile_spdk --tag simplyblock/spdk-core:BRANCH_NAME-amd64 .

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: hamdysimplyblock
        password: ${{ secrets.DOCKER_PASS }}

    - name: Push Images
      run: docker push simplyblock/spdk-core:$BRANCH_NAME-amd64

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_HAMDI }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_HAMDI }}
        aws-region: us-east-1

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Tag docker image
      run: docker tag simplyblock/spdk-core:$BRANCH_NAME-amd64 565979732541.dkr.ecr.us-east-1.amazonaws.com/spdk-core:$BRANCH_NAME-amd64

    - name: Push the docker image
      run: docker image push 565979732541.dkr.ecr.us-east-1.amazonaws.com/spdk-core:$BRANCH_NAME-amd64
    - name: Create the manifest
      run: |
        docker manifest create simplyblock/spdk-core:$BRANCH_NAME-latest simplyblock/spdk-core:arm64 simplyblock/spdk-core:$BRANCH_NAME-amd64
        docker manifest create 565979732541.dkr.ecr.us-east-1.amazonaws.com/spdk-core:$BRANCH_NAME-latest 565979732541.dkr.ecr.us-east-1.amazonaws.com/spdk-core:$BRANCH_NAME-arm64 565979732541.dkr.ecr.us-east-1.amazonaws.com/spdk-core:$BRANCH_NAME-amd64
        docker manifest annotate simplyblock/spdk-core:$BRANCH_NAME-latest simplyblock/spdk-core:$BRANCH_NAME-arm64 --arch arm64
        docker manifest annotate simplyblock/spdk-core:$BRANCH_NAME-latest simplyblock/spdk-core:$BRANCH_NAME-amd64 --arch amd64
        docker manifest annotate 565979732541.dkr.ecr.us-east-1.amazonaws.com/spdk-core:$BRANCH_NAME-latest 565979732541.dkr.ecr.us-east-1.amazonaws.com/spdk-core:$BRANCH_NAME-arm64 --arch arm64
        docker manifest annotate 565979732541.dkr.ecr.us-east-1.amazonaws.com/spdk-core:$BRANCH_NAME-latest 565979732541.dkr.ecr.us-east-1.amazonaws.com/spdk-core:$BRANCH_NAME-amd64 --arch amd64
        docker manifest push simplyblock/spdk-core:$BRANCH_NAME-latest
